### ISSUE TITLE
Cannot get respond

### ISSUE THREAD

**Issue by GanjinZero** [myzWILLmake/bgmgo#1]
```
bgmgo_windows_amd64.exe find jojo
Error: Get https://share.dmhy.org/topics/list?keyword=jojo: dial tcp 69.171.229.73:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Not found any result, please check your pattern
```
My environment is Windows 10. By using vpn or not, I get same respond problem.

**Comment by myzWILLmake** [comment]
If you live in China, [DMHY](https://share.dmhy.org) is banned by GFW.
So use a proxy to get access.
Or update to v0.2 which is using [bangumi.moe](https://bangumi.moe/) as the default data source.
